cp ~/git/BMMB554/hugo/static/img/pA.png  ./
cp ~/git/BMMB554/hugo/static/img/pB.png  ./
cp ~/git/BMMB554/hugo/static/img/pAB.png  ./
cp ~/git/BMMB554/hugo/static/img/freebayes.png ./
cp ~/git/BMMB554/hugo/static/img/library_import.png ./
cp ~/git/BMMB554/hugo/static/img/history_import.png ./
cp ~/git/BMMB554/hugo/static/img/library_import_complete.png ./
cp ~/git/BMMB554/hugo/static/img/FreeBayes_settings.png ./
cp ~/git/BMMB554/hugo/static/img/vcfallelicprimitives.png ./
cp ~/git/BMMB554/hugo/static/img/snpeff.png ./
cp ~/git/BMMB554/hugo/static/img/snpeff_chart.png ./
cp ~/git/BMMB554/hugo/static/img/snpeff_codons.png ./
cp ~/git/BMMB554/hugo/static/img/gemini_load.png ./
cp ~/git/BMMB554/hugo/static/img/gemini_db_info.png ./
cp ~/git/BMMB554/hugo/static/img/gemini_query1.png ./
cp ~/git/BMMB554/hugo/static/img/gemini_query2.png ./
cp ~/git/BMMB554/hugo/static/img/side-by-side.png ./
cp ~/git/BMMB554/hugo/static/img/gemini_command.png ./
cp ~/git/BMMB554/hugo/static/img/galaxy_command.png ./
