wget https://galaxyproject.org/galaxy101/manyDatasets.png
wget https://galaxyproject.org/galaxy101/historyItemControls.png
wget https://galaxyproject.org/galaxy101/historyWithCheckboxes.png
wget https://galaxyproject.org/galaxy101/forAllSelected.png
wget https://galaxyproject.org/galaxy101/buildPairs.png
wget https://galaxyproject.org/galaxy101/collectionCreation.png
wget https://galaxyproject.org/galaxy101/collectionCreationClean.png
wget https://galaxyproject.org/galaxy101/1and2.png
wget https://galaxyproject.org/galaxy101/collectionPrefiltered.png
wget https://galaxyproject.org/galaxy101/collectionCreation.png
wget https://galaxyproject.org/galaxy101/collectionNaming.png
wget https://galaxyproject.org/galaxy101/collection_ABCD.png
wget https://galaxyproject.org/galaxy101/bwa_mem_collection_readGroups.png
wget https://galaxyproject.org/galaxy101/bwa_memCollectionRunning.png
wget https://galaxyproject.org/galaxy101/bwa_memCollectionDone.png
wget https://galaxyproject.org/galaxy101/bwa_memCollection_ABC.png
wget https://galaxyproject.org/galaxy101/cleanSam.png
wget https://galaxyproject.org/galaxy101/folder.png
wget https://galaxyproject.org/galaxy101/cleanSam_closeup.png
wget https://galaxyproject.org/galaxy101/filter.png
wget https://galaxyproject.org/galaxy101/filter_closeup.png
wget https://galaxyproject.org/galaxy101/merge.png
wget https://galaxyproject.org/galaxy101/merge_closeup.png
wget https://galaxyproject.org/galaxy101/downsample.png
wget https://galaxyproject.org/galaxy101/downsample_closeup.png
wget https://galaxyproject.org/galaxy101/browserLinks.png
wget https://galaxyproject.org/galaxy101/igv.png
