cp ~/git/BMMB554/hugo/static/img/pe_mp.png ./
cp ~/git/BMMB554/hugo/static/img/illumina_qs.png ./
cp ~/git/BMMB554/hugo/static/img/fastq_qs.png ./
cp ~/git/BMMB554/hugo/static/img/cached_genome.png ./
cp ~/git/BMMB554/hugo/static/img/uploaded_genome.png ./
cp ~/git/BMMB554/hugo/static/img/bam_structure.png ./
cp ~/git/BMMB554/hugo/static/img/sam_fields.png ./
cp ~/git/BMMB554/hugo/static/img/sam_flag.png ./
cp ~/git/BMMB554/hugo/static/img/cigar.png ./
cp ~/git/BMMB554/hugo/static/img/rg.png ./
cp ~/git/BMMB554/hugo/static/img/rg_example.png ./
cp ~/git/BMMB554/hugo/static/img/pcr-duplicates.png ./
cp ~/git/BMMB554/hugo/static/img/sampling-bias.png ./
