/**
 * Hand-written screenplay data for the animated agent shells on
 * /tools/ai-agents/ ("Galaxy for AI Coding Agents").
 *
 * Every command, menu path, prompt syntax and verification step mirrors the
 * guide pages under content/tools/ai-agents/<harness>/index.md. When a guide
 * changes (commands, plugin names, skill invocations), update the matching
 * scene here, including its `copy` block. Tool results (username, versions,
 * job counts) are illustrative; no real credentials appear anywhere.
 */
import type { Scene } from './types';

const WHOAMI = 'Connect to Galaxy and tell me who I am.';
const WHOAMI_RESULT = 'username: jdoe · usegalaxy.org · Galaxy 26.0';
const WHOAMI_REPLY = 'You are jdoe on usegalaxy.org, which runs Galaxy 26.0.';

export const scenes: Scene[] = [
  // ---------------------------------------------------------------- Claude Code
  {
    id: 'claude-code',
    name: 'Claude Code',
    tagline: 'Plugin marketplace; prompts for URL and key at install',
    href: '#guide-claude-code',
    accent: '#d97757',
    monogram: 'CC',
    kind: 'terminal',
    title: 'claude — ~/chrM-variants',
    promptSymbol: '❯',
    slashPrefix: '/',
    copy: [
      '/plugin marketplace add galaxyproject/agentic-plugins',
      '/plugin install galaxy-mcp@galaxyproject',
      '/plugin install galaxy-skills@galaxyproject',
      '/plugin install galaxy-dev-skills@galaxyproject',
      '/plugin install foundry-skills@galaxyproject',
    ].join('\n'),
    lines: [
      { kind: 'cmd', text: 'claude', prompt: '$' },
      { kind: 'slash', text: 'plugin marketplace add galaxyproject/agentic-plugins' },
      { kind: 'out', text: 'Added marketplace galaxyproject', tone: 'ok', delay: 700 },
      { kind: 'slash', text: 'plugin install galaxy-mcp@galaxyproject' },
      { kind: 'field', label: 'Galaxy URL', value: 'https://usegalaxy.org' },
      { kind: 'field', label: 'API key', value: '••••••••', secret: true },
      {
        kind: 'spinner',
        text: 'Installing galaxy-mcp@galaxyproject…',
        done: 'Installed galaxy-mcp 0.1.0 · key saved to keychain',
        ms: 1400,
      },
      { kind: 'slash', text: 'plugin install galaxy-skills@galaxyproject' },
      {
        kind: 'spinner',
        text: 'Installing galaxy-skills@galaxyproject…',
        done: 'Installed galaxy-skills 2026.9.16',
        ms: 1100,
      },
      { kind: 'out', text: 'Start a new session to load the plugins.', tone: 'dim', delay: 500 },
      { kind: 'clear' },
      { kind: 'cmd', text: 'claude', prompt: '$' },
      { kind: 'slash', text: 'mcp' },
      { kind: 'out', text: 'galaxy · galaxy-mcp plugin · connected', tone: 'ok', delay: 600 },
      { kind: 'user', text: WHOAMI },
      { kind: 'tool', name: 'get_user', result: WHOAMI_RESULT, delay: 900 },
      { kind: 'assistant', text: WHOAMI_REPLY },
      { kind: 'user', text: "Upload both FASTQ files to a new history 'run 12' and run FastQC." },
      { kind: 'tool', name: 'create_history', args: 'run 12', result: 'history created', delay: 700 },
      {
        kind: 'tool',
        name: 'upload_file',
        args: 'run12_R1.fastq.gz, run12_R2.fastq.gz → run 12',
        result: '2 datasets · fastqsanger.gz',
        delay: 1300,
      },
      { kind: 'tool', name: 'search_tools_by_name', args: 'fastqc', result: 'FastQC 0.74+galaxy1', delay: 800 },
      { kind: 'tool', name: 'run_tool', args: 'fastqc × 2', result: '2 jobs queued', delay: 1000 },
      { kind: 'assistant', text: "Created 'run 12', uploaded both reads and queued FastQC on each." },
      { kind: 'pause', ms: 2500 },
    ],
  },

  // ---------------------------------------------------------------- Codex CLI
  {
    id: 'codex',
    name: 'Codex CLI',
    tagline: 'codex plugin add; credentials from your shell environment',
    href: '#guide-codex',
    accent: '#10a37f',
    monogram: 'Cx',
    kind: 'terminal',
    title: 'codex — ~/chrM-variants',
    promptSymbol: '›',
    slashPrefix: '$',
    copy: [
      'codex plugin marketplace add galaxyproject/agentic-plugins',
      'codex plugin add galaxy-mcp@galaxyproject',
      'codex plugin add galaxy-skills@galaxyproject',
      'codex plugin add galaxy-dev-skills@galaxyproject',
      'codex plugin add foundry-skills@galaxyproject',
    ].join('\n'),
    lines: [
      { kind: 'cmd', text: 'export GALAXY_URL="https://usegalaxy.org"', prompt: '$' },
      { kind: 'cmd', text: 'export GALAXY_API_KEY="paste-your-key-here"', prompt: '$' },
      { kind: 'cmd', text: 'codex plugin marketplace add galaxyproject/agentic-plugins', prompt: '$' },
      { kind: 'out', text: 'Added marketplace galaxyproject', tone: 'ok', delay: 700 },
      { kind: 'cmd', text: 'codex plugin add galaxy-mcp@galaxyproject', prompt: '$' },
      {
        kind: 'spinner',
        text: 'Installing galaxy-mcp@galaxyproject…',
        done: 'Installed galaxy-mcp 0.1.0',
        ms: 1200,
      },
      { kind: 'cmd', text: 'codex plugin add galaxy-skills@galaxyproject', prompt: '$' },
      {
        kind: 'spinner',
        text: 'Installing galaxy-skills@galaxyproject…',
        done: 'Installed galaxy-skills 2026.9.16',
        ms: 1000,
      },
      { kind: 'clear' },
      { kind: 'cmd', text: 'codex mcp list', prompt: '$' },
      { kind: 'out', text: 'galaxy   uvx galaxy-mcp   enabled', tone: 'ok', delay: 500 },
      { kind: 'out', text: 'GALAXY_URL=https://usegalaxy.org  GALAXY_API_KEY=****', tone: 'dim' },
      { kind: 'cmd', text: 'codex', prompt: '$' },
      { kind: 'user', text: WHOAMI },
      { kind: 'tool', name: 'get_user', result: WHOAMI_RESULT, delay: 900 },
      { kind: 'assistant', text: WHOAMI_REPLY },
      { kind: 'user', text: "Find an IWC paired-end variant-calling workflow; run it on 'run 12'." },
      {
        kind: 'tool',
        name: 'search_iwc_workflows',
        args: 'variant calling paired-end',
        result: 'generic-variant-calling-wgs-pe · 1 match',
        delay: 1000,
      },
      {
        kind: 'tool',
        name: 'import_workflow_from_iwc',
        args: 'generic-variant-calling-wgs-pe',
        result: 'imported · 15 steps',
        delay: 900,
      },
      {
        kind: 'tool',
        name: 'invoke_workflow',
        args: 'Generic variant calling (WGS PE) → run 12',
        result: 'invocation started',
        delay: 1100,
      },
      { kind: 'assistant', text: "Workflow running on 'run 12': 15 steps queued, the VCF lands there." },
      { kind: 'pause', ms: 2500 },
    ],
  },

  // ---------------------------------------------------------------- Antigravity
  {
    id: 'antigravity',
    name: 'Antigravity',
    tagline: 'git clone, then agy plugin install per plugin directory',
    href: '#guide-antigravity',
    accent: '#4285f4',
    monogram: 'Ag',
    kind: 'terminal',
    title: 'agy — ~/chrM-variants',
    promptSymbol: '$',
    slashPrefix: '/',
    copy: [
      'git clone https://github.com/galaxyproject/agentic-plugins.git ~/.galaxy-agentic-plugins',
      'agy plugin install ~/.galaxy-agentic-plugins/plugins/galaxy-mcp',
      'agy plugin install ~/.galaxy-agentic-plugins/plugins/galaxy-skills',
      'agy plugin install ~/.galaxy-agentic-plugins/plugins/galaxy-dev-skills',
      'agy plugin install ~/.galaxy-agentic-plugins/plugins/foundry-skills',
    ].join('\n'),
    lines: [
      { kind: 'cmd', text: 'export GALAXY_URL="https://usegalaxy.org"' },
      { kind: 'cmd', text: 'export GALAXY_API_KEY="paste-your-key-here"' },
      {
        kind: 'cmd',
        text: 'git clone https://github.com/galaxyproject/agentic-plugins.git ~/.galaxy-agentic-plugins',
      },
      { kind: 'out', text: "Cloning into '~/.galaxy-agentic-plugins'...", tone: 'dim', delay: 900 },
      { kind: 'cmd', text: 'agy plugin install ~/.galaxy-agentic-plugins/plugins/galaxy-mcp' },
      { kind: 'out', text: 'Installed galaxy-mcp → ~/.gemini/config/plugins/galaxy-mcp', tone: 'ok', delay: 700 },
      { kind: 'cmd', text: 'agy plugin install ~/.galaxy-agentic-plugins/plugins/galaxy-skills' },
      {
        kind: 'out',
        text: 'Installed galaxy-skills → ~/.gemini/config/plugins/galaxy-skills',
        tone: 'ok',
        delay: 700,
      },
      { kind: 'cmd', text: 'agy' },
      { kind: 'clear' },
      { kind: 'slash', text: 'mcp' },
      { kind: 'out', text: 'galaxy-mcp_galaxy · running · uvx galaxy-mcp', tone: 'ok', delay: 600 },
      { kind: 'user', text: WHOAMI },
      { kind: 'tool', name: 'get_user', result: WHOAMI_RESULT, delay: 900 },
      { kind: 'assistant', text: WHOAMI_REPLY },
      { kind: 'slash', text: 'reproduciblify' },
      { kind: 'user', text: "Rebuild history 'run 12 (scratch)' as a clean, extractable analysis." },
      {
        kind: 'tool',
        name: 'get_history_details',
        args: 'run 12 (scratch)',
        result: '23 datasets · 9 tool runs',
        delay: 1000,
      },
      {
        kind: 'tool',
        name: 'get_history_contents',
        args: 'run 12 (scratch)',
        result: '3 dead ends · 2 tool versions mixed',
        delay: 1100,
      },
      {
        kind: 'tool',
        name: 'run_tool',
        args: '6 steps → run 12 (clean)',
        result: '6 jobs ok · one tool version each',
        delay: 1600,
      },
      { kind: 'assistant', text: "Rebuilt 6 steps in 'run 12 (clean)'; it now extracts as a workflow." },
      { kind: 'pause', ms: 2500 },
    ],
  },

  // ---------------------------------------------------------------- Pi
  {
    id: 'pi',
    name: 'Pi',
    tagline: 'pi install: the MCP adapter plus the plugins git package',
    href: '#guide-pi',
    accent: '#14b8a6',
    monogram: 'Pi',
    kind: 'terminal',
    title: 'pi — ~/chrM-variants',
    promptSymbol: '>',
    slashPrefix: '/skill:',
    copy: ['pi install npm:pi-mcp-adapter', 'pi install git:github.com/galaxyproject/agentic-plugins'].join('\n'),
    lines: [
      { kind: 'cmd', text: 'export GALAXY_URL="https://usegalaxy.org"', prompt: '$' },
      { kind: 'cmd', text: 'export GALAXY_API_KEY="paste-your-key-here"', prompt: '$' },
      { kind: 'cmd', text: 'pi install npm:pi-mcp-adapter', prompt: '$' },
      { kind: 'spinner', text: 'Installing npm:pi-mcp-adapter…', done: 'Installed pi-mcp-adapter', ms: 1500 },
      { kind: 'cmd', text: 'pi install git:github.com/galaxyproject/agentic-plugins', prompt: '$' },
      {
        kind: 'spinner',
        text: 'Cloning github.com/galaxyproject/agentic-plugins…',
        done: 'Installed agentic-plugins · skills + MCP config registered',
        ms: 1900,
      },
      { kind: 'cmd', text: 'pi', prompt: '$' },
      { kind: 'clear' },
      { kind: 'cmd', text: '/mcp' },
      {
        kind: 'out',
        text: 'galaxyproject_agentic_plugins__galaxy · connects on first use',
        tone: 'ok',
        delay: 800,
      },
      { kind: 'user', text: WHOAMI },
      {
        kind: 'tool',
        name: 'get_user',
        args: 'via mcp · galaxyproject_agentic_plugins__galaxy',
        result: WHOAMI_RESULT,
        delay: 1400,
      },
      { kind: 'assistant', text: WHOAMI_REPLY },
      { kind: 'user', text: "Which datasets in 'run 12' are in error, and why?" },
      { kind: 'tool', name: 'get_history_contents', args: 'run 12', result: '12 datasets · 2 in error', delay: 1100 },
      {
        kind: 'tool',
        name: 'get_job_details',
        args: 'fastqc on run12_R1, run12_R2',
        result: 'exit 137 · memory limit hit',
        delay: 1400,
      },
      { kind: 'assistant', text: 'Both FastQC jobs hit the memory limit; I can rerun them with more RAM.' },
      { kind: 'pause', ms: 2500 },
    ],
  },

  // ---------------------------------------------------------------- Claude Desktop
  {
    id: 'claude-desktop',
    name: 'Claude Desktop',
    tagline: 'One-click .mcpb bundle; no terminal, MCP server only',
    href: '#guide-claude-desktop',
    accent: '#d97757',
    monogram: 'CD',
    kind: 'desktop',
    title: 'Claude',
    promptSymbol: '',
    slashPrefix: '',
    copyLabel: 'Copy install steps',
    copy: [
      '1. Download galaxy-mcp.mcpb from github.com/galaxyproject/agentic-plugins/releases/latest',
      '2. Open it with Claude Desktop (or Settings > Extensions > Advanced settings > Install Extension...)',
      '3. Enter your Galaxy URL and API key, then click Install',
    ].join('\n'),
    lines: [
      {
        kind: 'ui',
        text: 'Download galaxy-mcp.mcpb',
        detail: 'github.com/galaxyproject/agentic-plugins · latest release',
      },
      {
        kind: 'ui',
        text: 'Open with Claude Desktop',
        detail: 'or Settings › Extensions › Advanced settings › Install Extension…',
      },
      { kind: 'ui', text: 'Install extension: Galaxy', detail: 'galaxy-mcp · galaxyproject' },
      { kind: 'field', label: 'Galaxy URL', value: 'https://usegalaxy.org' },
      { kind: 'field', label: 'Galaxy API key', value: '••••••••', secret: true },
      { kind: 'ui', text: 'Install', detail: 'key stored in system keychain' },
      {
        kind: 'spinner',
        text: 'First start: downloading galaxy-mcp…',
        done: 'Galaxy extension ready',
        ms: 3200,
      },
      { kind: 'clear' },
      { kind: 'ui', text: 'Settings › Extensions › Galaxy', detail: 'Enabled' },
      { kind: 'pause', ms: 1200 },
      { kind: 'ui', text: 'New chat' },
      { kind: 'user', text: WHOAMI },
      { kind: 'tool', name: 'get_user', result: WHOAMI_RESULT, delay: 1500 },
      { kind: 'assistant', text: WHOAMI_REPLY },
      { kind: 'user', text: 'Show my three most recent histories.' },
      {
        kind: 'tool',
        name: 'get_histories',
        args: 'limit 3',
        result: 'run 12 · chrM variants · RNA-seq QC',
        delay: 1400,
      },
      { kind: 'assistant', text: 'run 12 (today), chrM variants (Mon) and RNA-seq QC (Sep 3).' },
      { kind: 'user', text: "Run FastQC on both reads in 'run 12'." },
      { kind: 'tool', name: 'search_tools_by_name', args: 'fastqc', result: 'FastQC 0.74+galaxy1', delay: 1200 },
      { kind: 'tool', name: 'run_tool', args: 'fastqc × 2 · run 12', result: '2 jobs queued', delay: 1500 },
      { kind: 'assistant', text: "FastQC is queued on run12_R1 and run12_R2; reports land in 'run 12'." },
      { kind: 'pause', ms: 2500 },
    ],
  },
];

const cursor: Scene = {
  id: 'cursor',
  name: 'Cursor',
  tagline: 'Customize › From GitHub Repository; key via env vars',
  href: '#guide-cursor',
  accent: '#8b5cf6',
  monogram: 'Cu',
  kind: 'ide',
  title: 'fastp-wrapper — Cursor',
  promptSymbol: '$',
  slashPrefix: '/',
  copy: [
    '1. Customize > From GitHub Repository > galaxyproject/agentic-plugins',
    '2. Install galaxy-mcp and galaxy-skills (user or project scope)',
    '3. Developer: Reload Window',
  ].join('\n'),
  lines: [
    { kind: 'ui', text: 'Customize › From GitHub Repository' },
    { kind: 'field', label: 'Repository', value: 'galaxyproject/agentic-plugins' },
    {
      kind: 'out',
      text: 'galaxy-mcp · galaxy-skills · galaxy-dev-skills · foundry-skills',
      tone: 'dim',
      delay: 900,
    },
    { kind: 'ui', text: 'Install galaxy-mcp', detail: 'User scope' },
    { kind: 'spinner', text: 'Installing galaxy-mcp…', done: 'galaxy-mcp installed', ms: 1400 },
    { kind: 'ui', text: 'Install galaxy-skills', detail: 'User scope' },
    { kind: 'spinner', text: 'Installing galaxy-skills…', done: 'galaxy-skills installed', ms: 1100 },
    { kind: 'ui', text: 'Install galaxy-dev-skills', detail: 'User scope' },
    { kind: 'spinner', text: 'Installing galaxy-dev-skills…', done: 'galaxy-dev-skills installed', ms: 1100 },
    { kind: 'ui', text: 'Developer: Reload Window' },
    { kind: 'clear' },
    { kind: 'ui', text: 'Customize › MCP' },
    { kind: 'out', text: 'galaxy · enabled · uvx galaxy-mcp', tone: 'ok', delay: 600 },
    { kind: 'out', text: 'env: ${env:GALAXY_URL}, ${env:GALAXY_API_KEY}', tone: 'dim' },
    { kind: 'out', text: 'tools: get_user, get_histories, upload_file, run_tool, …', tone: 'dim' },
    { kind: 'user', text: WHOAMI },
    { kind: 'tool', name: 'get_user', result: WHOAMI_RESULT, delay: 900 },
    { kind: 'assistant', text: WHOAMI_REPLY },
    { kind: 'slash', text: 'nf-to-galaxy' },
    { kind: 'user', text: 'Convert modules/fastp/main.nf into a Galaxy tool wrapper and test it.' },
    {
      kind: 'tool',
      name: 'read_file',
      args: 'modules/fastp/main.nf',
      result: 'process FASTP · 2 inputs · 3 outputs',
      delay: 1100,
    },
    {
      kind: 'tool',
      name: 'write_file',
      args: 'tools/fastp/fastp.xml',
      result: 'wrapper + 1 test case',
      delay: 1500,
    },
    {
      kind: 'tool',
      name: 'run_terminal',
      args: 'planemo test tools/fastp/fastp.xml',
      result: 'All 1 test(s) executed passed.',
      delay: 1900,
    },
    { kind: 'assistant', text: 'fastp.xml mirrors the process inputs and outputs; planemo test passes.' },
    { kind: 'pause', ms: 2500 },
  ],
};

/** Harnesses held back from the page for now; kept so they can be re-added. */
export const heldBack: Scene[] = [cursor];
