/**
 * Shared helpers for building the Atom feeds generated by the feed endpoints
 * under src/pages (files named feed.atom.ts). Endpoints filter their content
 * collections and then delegate serialization to `buildAtomFeed`.
 */

export interface AtomEntry {
  title: string;
  /** Absolute URL of the entry; used for both `<id>` and `<link>`. */
  url: string;
  date?: Date | string | null;
  summary?: string;
  /** Atom `<category>` classifications, e.g. news vs event. */
  categories?: Array<{ term: string; label?: string }>;
}

export interface AtomFeedOptions {
  title: string;
  /** Absolute URL of the HTML page the feed covers; also used as the feed `<id>`. */
  alternateUrl: string;
  /** Absolute URL of the feed itself; used as the `rel="self"` link. */
  selfUrl: string;
  subtitle?: string;
  lastUpdated?: Date | string | null;
  authorName?: string;
  entries: AtomEntry[];
}

export function escapeXML(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function atomDate(value?: Date | string | null): string {
  if (!value) return new Date().toISOString();
  const date = value instanceof Date ? value : new Date(value);
  return date.toISOString();
}

export function eventLinkFromSlug(slug: string): string {
  const cleaned = slug.replace(/\/$/, '');
  const pathSlug = cleaned.startsWith('events/') ? cleaned.slice('events/'.length) : cleaned;
  return `/events/${pathSlug}/`;
}

export interface FeedStaticPath {
  params: Record<string, string | undefined>;
}

/**
 * Expand the feed routes discovered by an `import.meta.glob` of feed endpoints
 * into one concrete route per generated feed. Routes for static endpoints are
 * returned unchanged; routes with dynamic segments (e.g. `/tags/[tag]/feed.atom`)
 * are expanded by loading the endpoint and calling its `getStaticPaths`, so each
 * generated feed is listed and counted individually.
 *
 * @param modules   The `import.meta.glob` result (module path to lazy loader).
 * @param toRoute   Maps a module path to its route (e.g. `../tags/[tag]/feed.atom.ts`
 *   to `/tags/[tag]/feed.atom`) or `null` for non-feed modules.
 */
export async function expandFeedRoutes(
  modules: Record<string, () => Promise<unknown>>,
  toRoute: (modulePath: string) => string | null
): Promise<string[]> {
  const routes: string[] = [];
  for (const [modulePath, loader] of Object.entries(modules)) {
    const route = toRoute(modulePath);
    if (!route) continue;
    if (!route.includes('[')) {
      routes.push(route);
      continue;
    }
    try {
      const mod = (await loader()) as { getStaticPaths?: () => Promise<FeedStaticPath[]> };
      const paths = (await mod.getStaticPaths?.()) ?? [];
      for (const path of paths) {
        let concrete = route;
        let resolved = true;
        for (const [key, value] of Object.entries(path.params ?? {})) {
          if (value === undefined) {
            resolved = false;
            break;
          }
          concrete = concrete.split(`[${key}]`).join(value);
        }
        if (resolved) routes.push(concrete);
      }
    } catch (error) {
      console.warn(`Failed to expand dynamic feed route ${route}:`, error);
    }
  }
  return routes;
}

export function buildAtomFeed(options: AtomFeedOptions): string {
  const { title, alternateUrl, selfUrl, subtitle, lastUpdated, authorName = 'Galaxy Project', entries } = options;

  let atom = `<?xml version="1.0" encoding="utf-8"?>\n`;
  atom += `<feed xmlns="http://www.w3.org/2005/Atom">\n`;
  atom += `  <id>${selfUrl}</id>\n`;
  atom += `  <title>${escapeXML(title)}</title>\n`;
  atom += `  <updated>${atomDate(lastUpdated)}</updated>\n`;
  atom += `  <generator>Galaxy Hub</generator>\n`;
  atom += `  <author><name>${escapeXML(authorName)}</name></author>\n`;
  atom += `  <link rel="alternate" href="${alternateUrl}"/>\n`;
  atom += `  <link rel="self" href="${selfUrl}"/>\n`;
  if (subtitle) {
    atom += `  <subtitle>${escapeXML(subtitle)}</subtitle>\n`;
  }

  for (const entry of entries) {
    atom += `  <entry>\n`;
    atom += `    <title>${escapeXML(entry.title)}</title>\n`;
    atom += `    <id>${entry.url}</id>\n`;
    atom += `    <link href="${entry.url}"/>\n`;
    atom += `    <updated>${atomDate(entry.date)}</updated>\n`;
    for (const category of entry.categories ?? []) {
      const label = category.label ? ` label="${escapeXML(category.label)}"` : '';
      atom += `    <category term="${escapeXML(category.term)}"${label}/>\n`;
    }
    if (entry.summary) {
      atom += `    <summary>${escapeXML(entry.summary)}</summary>\n`;
    }
    atom += `  </entry>\n`;
  }

  atom += `</feed>`;
  return atom;
}
