wget http://galaxy.psu.edu/galaxy101/newWindow.png
wget https://galaxyproject.org/galaxy101/twoScreens.png
wget http://galaxy.psu.edu/galaxy101/register.png
wget http://galaxy.psu.edu/galaxy101/getDataUCSC.png
wget http://galaxy.psu.edu/galaxy101/ucscGenes.png
wget http://galaxy.psu.edu/galaxy101/ucscGenes2.png
wget http://galaxy.psu.edu/galaxy101/firstHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/getDataUCSC.png
wget http://galaxy.psu.edu/galaxy101/variation.png
wget http://galaxy.psu.edu/galaxy101/ucscSNPs.png
wget http://galaxy.psu.edu/galaxy101/ucscSNPs2.png
wget http://galaxy.psu.edu/galaxy101/secondHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/rename.png
wget http://galaxy.psu.edu/galaxy101/join.png
wget http://galaxy.psu.edu/galaxy101/thirdHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/group1.png
wget http://galaxy.psu.edu/galaxy101/group2.png
wget http://galaxy.psu.edu/galaxy101/fourthHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/sort.png
wget http://galaxy.psu.edu/galaxy101/fifthHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/selectFirst.png
wget http://galaxy.psu.edu/galaxy101/sixthHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/compare.png
wget http://galaxy.psu.edu/galaxy101/seventhHistoryItem.png
wget http://galaxy.psu.edu/galaxy101/browsers.png
wget http://galaxy.psu.edu/galaxy101/ucsc.png
wget http://galaxy.psu.edu/galaxy101/seventhHistoryItem.png
wget http://galaxyproject.org/galaxy101/fa-columns.png
wget http://galaxyproject.org/galaxy101/historyDetail.png
wget http://galaxyproject.org/galaxy101/fa-cog.png
wget http://galaxy.psu.edu/galaxy101/historyOptions.png
wget http://galaxy.psu.edu/galaxy101/historyList.png
wget http://galaxyproject.org/galaxy101/fa-columns.png
wget http://galaxyproject.org/galaxy101/multiHistoryView.png
wget http://galaxyproject.org/galaxy101/orderingHistories.png
wget http://galaxy.psu.edu/galaxy101/historyCollapsed.png
wget http://galaxyproject.org/galaxy101/fa-cog.png
wget http://galaxy.psu.edu/galaxy101/extractWorkflow.png
wget http://galaxy.psu.edu/galaxy101/createWorkflow.png
wget http://galaxy.psu.edu/galaxy101/wfEditor.png
wget http://galaxy.psu.edu/galaxy101/hideStep.png
wget http://galaxy.psu.edu/galaxy101/lastStep.png
wget http://galaxy.psu.edu/galaxy101/workflowOverview.png
wget http://galaxy.psu.edu/galaxy101/namingInputs1.png
wget http://galaxy.psu.edu/galaxy101/renameExons.png
wget http://galaxy.psu.edu/galaxy101/renameFeatures.png
wget http://galaxy.psu.edu/galaxy101/addAction.png
wget http://galaxy.psu.edu/galaxy101/topExons.png
wget http://galaxy.psu.edu/galaxy101/runtimeTool.png
wget http://galaxy.psu.edu/galaxy101/paramSymbol.png
wget http://galaxy.psu.edu/galaxy101/runtimeParam.png
wget http://galaxyproject.org/galaxy101/fa-cog.png
wget http://galaxy.psu.edu/galaxy101/wfSave.png
wget http://galaxyproject.org/galaxy101/fa-cog.png
wget http://galaxy.psu.edu/galaxy101/createNewHistory.png
wget http://galaxy.psu.edu/galaxy101/getAllGenes.png
wget http://galaxy.psu.edu/galaxy101/ucscGenes2.png
wget http://galaxy.psu.edu/galaxy101/allRepeats.png
wget http://galaxy.psu.edu/galaxy101/allRepeats2.png
wget http://galaxy.psu.edu/galaxy101/runWorkflowButton.png
wget http://galaxy.psu.edu/galaxy101/launchWorkflow.png
wget http://galaxy.psu.edu/galaxy101/launchedWorkflow.png
wget http://galaxy.psu.edu/galaxy101/final.png
wget http://galaxy.psu.edu/galaxy101/importHistory.png
