cp ~/git/training-material/RNA-Seqtps://upload.wikimedia.org/wikipedia/commons/f/f0/Hematopoiesis_simple.svg ./
cp ~/git/training-material/RNA-Seq/images/trimmomatic.png ./
cp ~/git/training-material/RNA-Seq/images/BeforeAndAfterTrimming.png ./
cp ~/git/training-material/RNA-Seq/images/hisat_tool_form.png ./
cp ~/git/training-material/RNA-Seq/images/Stringtie.png ./
cp ~/git/training-material/RNA-Seq/images/Cuffmerge.png ./
cp ~/git/training-material/RNA-Seq/images/FeatureCounts_tool_form.png ./
cp ~/git/training-material/RNA-Seq/images/DESeq2_pval.png ./
cp ~/git/training-material/RNA-Seq/images/DESeq2_MAplot.png ./
cp ~/git/training-material/RNA-Seq/images/DESeq2_PCAplot.png ./
cp ~/git/training-material/RNA-Seq/images/DESeq2_heatmap_G1E_mega.png ./
cp ~/git/training-material/RNA-Seq/images/DESeq2_dispersion1.png ./
cp ~/git/training-material/RNA-Seq/images/bamCoverage_forward.png ./
cp ~/git/training-material/RNA-Seq/images/bamCoverage_reverse.png ./
cp ~/git/training-material/RNA-Seq/images/Trackster_opening_window.png ./
cp ~/git/training-material/RNA-Seq/images/Trackster_viz_hoxb13_locus.png ./
cp ~/git/training-material/RNA-Seq/images/schematic_for_RNAseq_de_novo_tutorial.png ./
