cp ~/git/training-material/Usegalaxy/images/ref_vs_assembly.jpg ./
cp ~/git/training-material/Usegalaxy/images/mt_lib.png ./
cp ~/git/training-material/Usegalaxy/images/mt_imported_data.png ./
cp ~/git/training-material/Usegalaxy/images/mt_qc.png ./
cp ~/git/training-material/Usegalaxy/images/mt_middle_button.png ./
cp ~/git/training-material/Usegalaxy/images/mt_qc_plot.png ./
cp ~/git/training-material/Usegalaxy/images/mt_bwa_mem.png ./
cp ~/git/training-material/Usegalaxy/images/mt_middle_button.png ./
cp ~/git/training-material/Usegalaxy/images/mt_bam_merging.png ./
cp ~/git/training-material/Usegalaxy/images/mt_dedup.png ./
cp ~/git/training-material/Usegalaxy/images/mt_left_align.png ./
cp ~/git/training-material/Usegalaxy/images/mt_filtering.png ./
cp ~/git/training-material/Usegalaxy/images/mt_freebayes_genome.png ./
cp ~/git/training-material/Usegalaxy/images/mt_freebayes_regions.png ./
cp ~/git/training-material/Usegalaxy/images/mt_freebayes_alloptions.png ./
cp ~/git/training-material/Usegalaxy/images/mt_freebayes_popmodel.png ./
cp ~/git/training-material/Usegalaxy/images/mt_freebayes_allelic_scope.png ./
cp ~/git/training-material/Usegalaxy/images/mt_freebayes_inputfilters.png ./
cp ~/git/training-material/Usegalaxy/images/mt_biases.png ./
cp ~/git/training-material/Usegalaxy/images/freebayes.pdf ./
cp ~/git/training-material/Usegalaxy/images/mt_vcffilter.png ./
cp ~/git/training-material/Usegalaxy/images/mt_vcf_dataset_collapsed.png ./
cp ~/git/training-material/Usegalaxy/images/mt_vcf_dataset_expanded.png ./
cp ~/git/training-material/Usegalaxy/images/mt_vcfiobio.png ./
cp ~/git/training-material/Usegalaxy/images/mt_vcf_dataset_expanded.png ./
cp ~/git/training-material/Usegalaxy/images/mt_igv.png ./
cp ~/git/training-material/Usegalaxy/images/mt_vcfToTab.png ./
cp ~/git/training-material/Usegalaxy/images/mt_tab.png ./
cp ~/git/training-material/Usegalaxy/images/mt_cut.png ./
